### ISSUE TITLE
Fix debugging story

### ISSUE THREAD

**Issue by breerly** [uber/tchannel-python#100]
Been having trouble seeing what's going on while developing things - guessing this will bite our customers as well.

- [ ] should be able to enable a debug mode that will cause a server to send along it's stack trace when it receives an error
- [ ] internals aren't logging much - @abhinav can you elaborate here?

@blampe  you mentioned you might have a bit of bandwidth for this?

**Comment by abhinav** [comment]
The class responsible for calling the handler doesn't do much logging when it captures exceptions. We should add exception log entries where appropriate.

**Comment by blampe** [comment]
#108 should help with this.
