### ISSUE TITLE
Drop two-phase API in favor of single call method.

### ISSUE THREAD

**Issue by abhinav** [uber/tchannel-python#12]
The two phase `request(..).send(..)` API seems unnecessary. Let's converge it into a single call.

Assigning to @breerly  because he expressed interest in doing this.

**Comment by breerly** [comment]
Whipped up a gist for the proposed API. Please comment:

https://gist.github.com/breerly/ca4f6b9c17861327aa8a

**Comment by Grayson** [comment]
@abhinav, I believe you've tagged in the wrong Grayson.

**Comment by abhinav** [comment]
Oh, right. Yes, the `@` was wrong. Thanks.

**Comment by junchaowu** [comment]
Oh here it is.

**Comment by breerly** [comment]
fixed in 0.15.0
