### ISSUE TITLE
Default number of retries differs from node implementation

### ISSUE THREAD

**Issue by Willyham** [uber/tchannel-python#126]
I feel like these should be consistent. Node has 5, python has 4.

**Comment by junchaowu** [comment]
We take 4 because that's the number for retries and it doesn't count the first one. The first request doesn't belong to retry , it is a normal request. I synced with Jake last time. They don't mention what's retry and what's the first request. They just put them together.

**Comment by Willyham** [comment]
Got it, thanks.
