### ISSUE TITLE
Support specifying hyperbahn seed list list by filename.

### ISSUE THREAD

**Issue by blampe** [uber/tchannel-python#21]
https://github.com/uber/tchannel/issues/926

This would also help us reduce services all duplicating the location of the seed list on disk (clay-hyperbahn would default to the correct path).

**Comment by breerly** [comment]
Will do as part of server refactor

**Comment by abhinav** [comment]
@ShanniLi you took care of this, right?

**Comment by ShanniLi** [comment]
yes :)
