### ISSUE TITLE
document synchronous fanout

### ISSUE THREAD

**Issue by blampe** [uber/tchannel-python#210]
"How do I do fanout with the synchronous client?" This is a common question we get a lot.

@breerly @junchaowu @abhinav

**Comment by breerly** [comment]
Think we should drum up a **Synchronous Client Usage** section of the docs? 

Fanout looks a bit like this test (but from `tchannel.sync.TChannel`'s POV: https://github.com/breerly/threadloop/blob/master/tests/threadloop/test_threadloop.py#L203

**Comment by blampe** [comment]
totes
