### ISSUE TITLE
Add instrumentation behaviors, like mutornadomon but for TChannel.

### ISSUE THREAD

**Issue by blampe** [uber/tchannel-python#24]
https://github.com/uber/mutornadomon

This installs IOLoop hooks into an HTTP Tornado app. We need something similar for pure TChannel apps.

**Comment by emou** [comment]
Can we have a way for other modules to plug additional stats, i.e. if I want stats for the thread-pools I'm using, can you make it possible for me to plug them in here?

**Comment by blampe** [comment]
We expose some event hooks around TChannel, but hooks around thread pools and stuff would be installed at a different layer (like where we install these tchannel hooks).

**Comment by breerly** [comment]
Closing for now since the event hooks (soon to be refactored) expose everything one would need to hook into.

**Comment by blampe** [comment]
https://github.com/uber/mutornadomon/pull/12 added an interface to publish additional metrics and we can use that.
