### ISSUE TITLE
How to get the address of service through hyperbahn

### ISSUE THREAD

**Issue by simpleton** [uber/tchannel-python#301]
I only find the function(`advertise`) to register the server, but I didn't find the method to get a server with client.

**Comment by abhinav** [comment]
Hello. You don't query Hyperbahn for the remote host's address. Instead, you send the request to Hyperbahn with the remote service's name, and Hyperbahn will forward the request to the service, provided that it too is advertising.

**Comment by simpleton** [comment]
Hi @abhinav , thanks for your feedback.

Your answer makes me a little confused. As `Hyperbahn`'s introduction, it's a "Service discovery and routing system" . Actually I didn't know who are providing service. What's the remote service's name as you mentioned.

Could you provide a simple example for that? 

Your reply will be highly appreciate.

**Comment by blampe** [comment]
Hyperbahn exposes a discover endpoint for this purpose: https://github.com/uber/tchannel-node/blob/master/hyperbahn-client.js#L466
