### ISSUE TITLE
Useless requirements.txt

### ISSUE THREAD

**Issue by breerly** [uber/tchannel-python#334]
Not sure we added a requirements.txt which duplicates setup.py - AFAIK this is harmful, we should remove it.

@abhinav @junchaowu @blampe

**Comment by blampe** [comment]
@webmaven can weigh in. I think it basically boils down to workflow - `python setup.py install` vs. `pip install -r requirements.txt`. The latter would actually be more useful if we used `pip freeze` to generate the requirements.

**Comment by webmaven** [comment]
@blampe has it right regarding workflow. Generating requirements.txt with `pip freeze` would only nail the requirements to particular versions, though, which is probably not what you want.

**Comment by blampe** [comment]
There's value in both and the difference basically boils down to abstract dependencies vs. reproducible builds. `pip-compile` can help with the duplication between `setup.py` and `requirements.txt`, so I think we can keep this around and actually add a `requirements.in` for `setup.py` to source.

http://nvie.com/posts/better-package-management/
https://caremad.io/2013/07/setup-vs-requirement/
