### ISSUE TITLE
TransportHeaders.to_dict()

### ISSUE THREAD

**Issue by abhinav** [uber/tchannel-python#350]
We need an easy way for users to convert transport headers to/from the key-value dict that will actually be sent over the wire. A use case for this is if you're implementing a catch-all endpoint that needs to serialize the contents of the request for some reason (to send them to another server, for example), it also needs to record the transport headers. 

Side: This will be needed for VCR anyway when we actually remove the deprecated API.

**Comment by breerly** [comment]
AFAICT it should be easy enough to implement a `to_dict` function
