### ISSUE TITLE
Change default sampling rate for tracing to 1%

### ISSUE THREAD

**Issue by yurishkuro** [uber/tchannel-python#364]
The current default sampling rate of 100% is unheard of in distributed tracing. If deployed in a high-throughput service it can easily DDOS the tracing system.

https://github.com/uber/tchannel-python/blob/master/tchannel/zipkin/zipkin_trace.py#L32
```python
    DEFAULT_RATE = 1.0
```

**Comment by abhinav** [comment]
CC @junchaowu
