### ISSUE TITLE
Calling vcr.use_cassette reads/parses fixture file each time it's called

### ISSUE THREAD

**Issue by shubik22** [uber/tchannel-python#419]
I work on a project that uses tchannel-python and decorates a large number of tests with vcr.use_cassette to stub out tchannel calls.  It uses the same yaml file as a fixture everywhere it calls vcr.use_cassette.  It's a somewhat large yaml file; on my MacBook Pro, it takes about half a second to load/parse the file.

The issue is that each time vcr.use_cassette is called, the yaml file is loaded and parsed anew, adding at least 0.5 seconds to each test in the case above.  See [here](https://github.com/uber/tchannel-python/blob/master/tchannel/testing/vcr/cassette.py#L170):

```
    def _load(self):
        try:
            with open(self.path, 'rb') as f:
                data = f.read()
                self.existed = True
        except IOError:
            return  # nothing to read

        data = yaml.load(data)
        if not (data and 'interactions' in data):
            return  # file was probably empty

        if int(data['version']) != VERSION:
            raise UnsupportedVersionError(
                'Cassette at "%s" is an unsupported version of the '
                'format: version %s' % (self.path, str(data['version']))
            )

        self._available = [
            Interaction.to_native(i) for i in data['interactions']
        ]
```

I'd propose adding an optional cache for interactions loaded from a yaml file, so that users who have a read-only file used throughout their test suite can read/parse it once (rather than every time vcr.use_cassette is called).

I don't have a lot of experience with python, but the code would probably look something like this.  There'd be a cache class:

```
class _InteractionsCache(object):

    _cache = {}

    @classmethod
    def save_interactions(cls, path, interactions):
        cls._cache[path] = interactions

    @classmethod
    def load_interactions(cls, path):
        try:
            return deepcopy(cls._cache[path])
        except KeyError:
            return None

```

(Do I need to work about any sort of thread-safety issues with this kind of cache in Python?)

Then I'd modify Cassette._load (additions are the blocks starting with `if self.use_cache` at beginning and end of the method):

```
    def _load(self):
        if self.use_cache:
            interactions = _InteractionsCache.load_interactions(self.path)
            if interactions:
                self._available = interactions
                return

        try:
            with open(self.path, 'rb') as f:
                data = f.read()
                self.existed = True
        except IOError:
            return  # nothing to read

        data = yaml.load(data)
        if not (data and 'interactions' in data):
            return  # file was probably empty

        if int(data['version']) != VERSION:
            raise UnsupportedVersionError(
                'Cassette at "%s" is an unsupported version of the '
                'format: version %s' % (self.path, str(data['version']))
            )

        self._available = [
            Interaction.to_native(i) for i in data['interactions']
        ]
        if self.use_cache:
            _InteractionsCache.save_interactions(self.path, self._available)

```

Let me know if this seems like a reasonable idea and approach and I can put out a PR.  Any comments/suggestions/criticisms would be greatly appreciated.

**Comment by abhinav** [comment]
Rather than making the cache optional, what about a cache that is keyed off the hash of file and its path? That will make the cache safe to apply globally.

```python
            hash = None
            with open(self.path, 'rb') as f:
                hash = sha256(f)
                self.existed = True
                if self._cache[(self.path, hash)]:
                    self._available = deepcopy(self._cache[(self.path, hash)])
                    return
                data = f.read()

            # ...
            self._available = [...]
            if hash is not None:
                self._cache[(self.path, hash)] = deepcopy(self._available)
```

Where `self._cache` is the global class-level cache.

**Comment by shubik22** [comment]
Cool, that's a lot better.  I think you'd need to actually read the contents of the file in order to create the hash, but otherwise sounds like a good idea.  (Judging from some quick tests I did, it seems like that calling yaml.load is what takes up almost all of the setup time and that calling f.read() is relatively insignificant.)

Do you have any suggestions about the best way to test this?  I can test that the cache is being written to, but not sure how to check whether we're reading from the cache.

**Comment by abhinav** [comment]
An easy way to do it would be to monkey patch `yaml.load` and ensure that isn't called (since that's the call we're trying to eliminate). Without monkey-patching, we can inject the yaml parser into the Cassette at instantiation (defaulting to `yaml`), and provide a fake that fails if `load` gets called.

```python
import yaml

class Cassette(object)
  def __init__(self, ..., serializer=None):
    if serializer is None:
      serializer = yaml
    self.serializer = serializer
    # ...
```

And then use `self.serializer.load` and `self.serializer.dump` instead of `yaml.load` and `yaml.dump`.

**Comment by shubik22** [comment]
👍
