### ISSUE TITLE
Previous VCR recordings mismatch due to $tracing$ headers

### ISSUE THREAD

**Issue by yurishkuro** [uber/tchannel-python#430]
@abhinav @blampe 

Some users complained that if they have Jaeger enabled in unit tests, they are getting breaks due to `$tracing$` headers being included in the new messages and not included in the recorded messages. I think the simplest solution is to strip out the tracing headers when using VCR, wdyt?  Any pointers?

**Comment by yurishkuro** [comment]
cc @abeinstein

**Comment by blampe** [comment]
Does tracing need to be enabled in testing or could it be disabled to get around this?

**Comment by yurishkuro** [comment]
It can certainly be disabled, but then a recent bug in redis monkey-patching hit production while it could've been caught by tests.

**Comment by abhinav** [comment]
I'll try to fix this tomorrow.

**Comment by abhinav** [comment]
0.27.2 released with fix
