### ISSUE TITLE
Getting local IP on a Mac throws exception

### ISSUE THREAD

**Issue by johankj** [uber/tchannel-python#472]
In [tchannel/net.py:46](https://github.com/uber/tchannel-python/blob/938fd8e7a94984eaf620e4e0e3c18238dffcfa0f/tchannel/net.py#L44-L46) there is a function for getting the local IP.

This function uses `socket.gethostbyname(socket.gethostname())` which can throw an error (`gaierror: [Errno 8] nodename nor servname provided, or not known`) if [a valid address-to-host mapping doesn't exist for the host](https://docs.python.org/2/library/socket.html#socket.gethostname). This is the case when running on some Mac configurations.

On a Mac `socket.gethostname()` returns the hostname (the ‘Computer name’ defined in System Preferences » Sharing, e.g. 'MacBook-Pro'), but this is not always a valid address-to-host mapping on macOS. In that case the hostname to be used is 'MacBook-Pro.local'.

As a temporary workaround, a user can add their own machines hostname to /etc/hosts (i.e. adding the result of `echo 127.0.0.1 $(hostname)`). Although it would be preferable if this package could try to get the host by using `socket.gethostname() + '.local'` or defaulting to 127.0.0.1, if any errors are thrown.

The following might be a way to do it:
```
ip = '127.0.0.1'
try: 
    ip = socket.gethostbyname(socket.gethostname())
except socket.gaierror, e: 
    try: 
        ip = socket.gethostbyname(socket.gethostname() + '.local')
    except: pass
except: pass
```

**Comment by westover** [comment]
Fixed in #486
