### ISSUE TITLE
Add Thrift support to tcurl.py.

### ISSUE THREAD

**Issue by blampe** [uber/tchannel-python#6]
Right now python services need to awkwardly install node packages to be able to curl their service. Adding thrift support to `tcurl.py` would be easy and would enable this out of the box.

**Comment by breerly** [comment]
I sort of wonder if we should ditch our tcurl implementation, and instead allow the tcurl project to fulfill this requirement... it's a bit confusing that the python impl has a tcurl in addition to the main project

**Comment by blampe** [comment]
`tcurl.js` has a painful CLI (that we need to remedy) and it's reasonable to expect something out-of-the-box to debug you app without needing to npm install stuff locally.

**Comment by breerly** [comment]
@blampe I kind of expect tcurl to be available in all the package managers... I don't think it's unreasonable for a tchannel user to `brew install tcurl` tbh

**Comment by breerly** [comment]
@blampe also - we should probably fix `tcurl.js` interface instead of duplicating it

**Comment by blampe** [comment]
Available in 0.18.
