### ISSUE TITLE
Thrift headers only work with strings

### ISSUE THREAD

**Issue by breerly** [uber/tchannel-python#84]

**Comment by breerly** [comment]
@abhinav @blampe so this is the expected behavior... how should we deal with it then...

* test that header keys and values are string, raise error otherwise
* attempt to cast keys and values to strings, raise if unable
* EAFP - just attempt to send the damn thing, let the user try to figure out what happened...

**Comment by abhinav** [comment]
Option 3 makes sense to me. Caller should be able to pass in anything that our system is able to serialize without blowing up. `isinstance` checks seem restrictive, especially in use cases where alternative types will flow through just fine.

**Comment by blampe** [comment]
Does that mean stringify everything? So `{"foo": 1}` would come out as `{"foo": "1"}` on the other end?

**Comment by breerly** [comment]
closed by #89
